# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBasicdate():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_basicdate(self):
    self.driver.get("https://kronos.calvarycare.org.au/wfcstatic/applications/navigator/html5/dist/container/index.html?version=8.1.20.121")
    self.driver.set_window_size(1296, 1000)
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, ".hyperfind-location__edit-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".related-item:nth-child(5) .related-item__title").click()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.ID, "hyperfindComboBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#more > .ng-binding").click()
    self.driver.find_element(By.LINK_TEXT, "CAH-C9430-ICU").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#schedule\\.timeframe\\.selector .input-append > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # click calendar
    self.driver.find_element(By.XPATH, "//div[2]/button/i").click()
    # send data 1
    self.driver.find_element(By.XPATH, "//span/div/input").send_keys("11112024")
    # send date 2
    self.driver.find_element(By.XPATH, "//span[2]/div/div/div/span/div/input").send_keys("14122024")
    # apply date
    self.driver.find_element(By.XPATH, "//button[2]/span").click()
    self.driver.find_element(By.XPATH, "//span/span[2]").click()
    self.driver.find_element(By.XPATH, "//span/span[2]").click()



tester = TestBasicdate()
tester.setup_method()
tester.test_basicdate()